version: "3"

services:
  backend:
    image: "hacker-news-clone-spring:latest"
    container_name: "backend"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    env_file:
      - ./.env
    ports:
      - "8080:8080"
  database:
    image: "mongo:latest"
    container_name: "mongo"
    ports:
      - "27017:27017"